# Generated by Django 4.1 on 2025-04-30 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=60)),
                ('aula', models.CharField(max_length=10)),
                ('fecha_hora', models.DateTimeField()),
                ('alumno', models.ManyToManyField(related_name='asignaturas', to='blog.alumno')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clase', to='blog.carrera')),
            ],
        ),
    ]
